/**
 * TSM Enterprise Runtime Loader
 *
 * Loads all 251 capability files across the 41-namespace runtime tree in
 * dependency-safe order via sequential <script> injection (no bundler in this
 * project, so this is the load-order guarantee). Tier 0 (event-bus/relay/
 * rule-registry/adapter-registry) loads first since runtime.js reads them at
 * load time. Tier 1 (agent-registry.js) loads before agents/agents/*.js, which
 * self-register into it. rules/*.js self-register into the root rule-registry.js
 * the same way. index.js (the health-check bootstrap) is loaded explicitly LAST,
 * after every capability file, so its readiness check reflects true final state.
 *
 * Usage: <script src="/shared/runtime/runtime-loader.js"></script>
 * Then listen for the TSM_RUNTIME_LOADED event, or poll window.TSMRuntimeHealth.
 */
(function () {
  var BASE = '/shared/runtime/';
  var FILES = [
  "event-bus.js",
  "relay.js",
  "rule-registry.js",
  "adapter-registry.js",
  "agents/agent-registry.js",
  "runtime.js",
  "adapters/bpo-runtime-adapter.js",
  "adapters/construction-runtime-adapter.js",
  "adapters/finops-runtime-adapter.js",
  "adapters/healthcare-runtime-adapter.js",
  "adapters/insurance-runtime-adapter.js",
  "adapters/legal-runtime-adapter.js",
  "adapters/mdm-runtime-adapter.js",
  "adapters/realestate-runtime-adapter.js",
  "agents/agent-engine.js",
  "agents/agent-executor.js",
  "agents/agent-memory.js",
  "agents/agent-planner.js",
  "agents/agent-router.js",
  "ai/orchestrator.js",
  "approval/approval-engine.js",
  "assistant/action-planner.js",
  "assistant/assistant-engine.js",
  "assistant/command-router.js",
  "assistant/context-manager.js",
  "assistant/conversation-memory.js",
  "assistant/intent-parser.js",
  "assistant/response-generator.js",
  "autonomy/adaptive-rules.js",
  "autonomy/agent-collaboration.js",
  "autonomy/autonomous-workflows.js",
  "autonomy/autonomy-engine.js",
  "autonomy/decision-loop.js",
  "autonomy/self-healing.js",
  "command-center/alert-center.js",
  "command-center/command-feed.js",
  "command-center/dashboard-engine.js",
  "command-center/executive-summary.js",
  "command-center/kpi-engine.js",
  "command-center/risk-board.js",
  "commercial/account-intelligence.js",
  "commercial/billing-intelligence.js",
  "commercial/entitlement-manager.js",
  "commercial/roi-engine.js",
  "commercial/subscription-engine.js",
  "commercial/usage-meter.js",
  "connectors/api-gateway.js",
  "connectors/connector-engine.js",
  "connectors/connector-health.js",
  "connectors/credential-manager.js",
  "connectors/integration-registry.js",
  "connectors/sync-orchestrator.js",
  "connectors/webhook-manager.js",
  "constants.js",
  "control-plane/configuration-manager.js",
  "control-plane/dependency-manager.js",
  "control-plane/feature-control.js",
  "control-plane/health-monitor.js",
  "control-plane/runtime-governor.js",
  "control-plane/runtime-orchestrator.js",
  "control-plane/version-manager.js",
  "customer/configuration-wizard.js",
  "customer/customer-health.js",
  "customer/migration-manager.js",
  "customer/onboarding-engine.js",
  "customer/solution-packager.js",
  "customer/tenant-provisioner.js",
  "data/data-governance.js",
  "data/data-quality.js",
  "data/entity-resolution.js",
  "data/lineage-engine.js",
  "data/master-index.js",
  "data/semantic-layer.js",
  "decision-surface/command-interface.js",
  "decision-surface/decision-dashboard.js",
  "decision-surface/decision-history.js",
  "decision-surface/executive-insights.js",
  "decision-surface/opportunity-engine.js",
  "decision-surface/recommendation-center.js",
  "decision-surface/risk-intelligence.js",
  "deployment/environment-manager.js",
  "deployment/migration-engine.js",
  "deployment/rollback-engine.js",
  "deployment/tenant-deployment.js",
  "deployment/upgrade-manager.js",
  "digital-twin/entity-registry.js",
  "digital-twin/relationship-engine.js",
  "digital-twin/snapshot-store.js",
  "digital-twin/state-engine.js",
  "digital-twin/state-query.js",
  "digital-twin/twin-health.js",
  "ecosystem/capability-discovery.js",
  "ecosystem/ecosystem-analytics.js",
  "ecosystem/marketplace-intelligence.js",
  "ecosystem/partner-manager.js",
  "ecosystem/partner-registry.js",
  "ecosystem/revenue-sharing.js",
  "ecosystem/solution-composer.js",
  "event-mesh/anomaly-detector.js",
  "event-mesh/event-correlation.js",
  "event-mesh/event-history.js",
  "event-mesh/event-processor.js",
  "event-mesh/intelligence-stream.js",
  "event-mesh/pattern-detector.js",
  "event-mesh/signal-router.js",
  "execution/action-executor.js",
  "execution/automation-engine.js",
  "execution/learning-engine.js",
  "execution/notification-engine.js",
  "execution/sla-monitor.js",
  "execution/workflow-engine.js",
  "explainability/explanation-engine.js",
  "governance/access-control.js",
  "governance/audit-engine.js",
  "governance/compliance-engine.js",
  "governance/decision-log.js",
  "governance/evidence-store.js",
  "governance/policy-engine.js",
  "graph/dependency-map.js",
  "graph/entity-graph.js",
  "graph/graph-memory.js",
  "graph/graph-query.js",
  "graph/impact-analysis.js",
  "graph/relationship-engine.js",
  "identity/access-recommendation.js",
  "identity/behavior-model.js",
  "identity/privilege-analyzer.js",
  "identity/role-intelligence.js",
  "identity/user-profile-engine.js",
  "integration/api-gateway.js",
  "integration/connector-registry.js",
  "integration/crm-connector.js",
  "integration/data-mapper.js",
  "integration/data-sync-engine.js",
  "integration/document-connector.js",
  "integration/erp-connector.js",
  "integration/event-ingestion.js",
  "integration/event-stream.js",
  "integration/integration-engine.js",
  "integration/integration-health.js",
  "integration/sync-engine.js",
  "intelligence/cross-domain-engine.js",
  "intelligence/cross-mesh.js",
  "intelligence/exception-engine.js",
  "knowledge/answer-engine.js",
  "knowledge/context-engine.js",
  "knowledge/document-intelligence.js",
  "knowledge/knowledge-engine.js",
  "knowledge/knowledge-governance.js",
  "knowledge/knowledge-graph.js",
  "knowledge/semantic-search.js",
  "marketplace/capability-catalog.js",
  "marketplace/dependency-resolver.js",
  "marketplace/extension-registry.js",
  "marketplace/extension-validator.js",
  "marketplace/plugin-loader.js",
  "marketplace/sandbox-manager.js",
  "marketplace/version-manager.js",
  "memory/embedding-index.js",
  "memory/historical-memory.js",
  "memory/knowledge-store.js",
  "memory/memory-engine.js",
  "memory/pattern-engine.js",
  "memory/recommendation-engine.js",
  "mission/mission-engine.js",
  "mission/mission-router.js",
  "mission/mission-store.js",
  "model-governance/hallucination-monitor.js",
  "model-governance/model-cost-optimizer.js",
  "model-governance/model-evaluation.js",
  "model-governance/model-registry.js",
  "model-governance/model-routing.js",
  "observability/cost-intelligence.js",
  "observability/event-tracing.js",
  "observability/metrics-engine.js",
  "observability/performance-monitor.js",
  "observability/runtime-dashboard.js",
  "observability/usage-analytics.js",
  "operations/backup-manager.js",
  "operations/deployment-manager.js",
  "operations/environment-manager.js",
  "operations/health-orchestrator.js",
  "operations/incident-manager.js",
  "operations/recovery-engine.js",
  "operations/release-manager.js",
  "optimization/automation-discovery.js",
  "optimization/benchmark-engine.js",
  "optimization/bottleneck-optimizer.js",
  "optimization/continuous-improvement.js",
  "optimization/efficiency-engine.js",
  "optimization/resource-optimizer.js",
  "policy-intelligence/compliance-mapper.js",
  "policy-intelligence/exception-policy.js",
  "policy-intelligence/policy-engine.js",
  "policy-intelligence/policy-evaluator.js",
  "policy-intelligence/policy-history.js",
  "policy-intelligence/policy-learning.js",
  "policy-intelligence/regulation-engine.js",
  "prediction/forecasting-engine.js",
  "prediction/recommendation-engine.js",
  "prediction/risk-prediction.js",
  "prediction/scenario-engine.js",
  "prediction/simulation-engine.js",
  "process-mining/process-discovery.js",
  "quality/quality-engine.js",
  "reasoning/causal-engine.js",
  "reasoning/evidence-ranker.js",
  "reasoning/hypothesis-generator.js",
  "reasoning/inference-engine.js",
  "reasoning/reasoning-engine.js",
  "reasoning/reasoning-history.js",
  "reasoning/relationship-analyzer.js",
  "security/authentication-engine.js",
  "security/authorization-engine.js",
  "security/encryption-manager.js",
  "security/secret-manager.js",
  "security/security-audit.js",
  "security/session-manager.js",
  "security/tenant-manager.js",
  "simulation/decision-simulator.js",
  "simulation/impact-calculator.js",
  "simulation/outcome-predictor.js",
  "simulation/scenario-manager.js",
  "simulation/simulation-engine.js",
  "simulation/simulation-history.js",
  "simulation/what-if-engine.js",
  "solution-packaging/pack-builder.js",
  "solution-packaging/pack-installer.js",
  "solution-packaging/pack-manifest-engine.js",
  "solution-packaging/pack-registry.js",
  "solution-packaging/pack-validator.js",
  "trust-evidence/approval-chain-tracker.js",
  "trust-evidence/audit-trail-engine.js",
  "trust-evidence/decision-provenance.js",
  "trust-evidence/evidence-ledger.js",
  "trust-evidence/outcome-tracker.js",
  "agents/agents/bpo-agent.js",
  "agents/agents/construction-agent.js",
  "agents/agents/finops-agent.js",
  "agents/agents/healthcare-agent.js",
  "agents/agents/insurance-agent.js",
  "agents/agents/legal-agent.js",
  "agents/agents/mdm-agent.js",
  "agents/agents/realestate-agent.js",
  "rules/bpo.js",
  "rules/construction.js",
  "rules/governance.js",
  "rules/healthcare.js",
  "rules/insurance.js",
  "rules/integration.js",
  "rules/mdm.js"
];

  function loadScript(src, onDone) {
    var s = document.createElement('script');
    s.src = src;
    s.onload = onDone;
    s.onerror = function () {
      console.error('[TSM RUNTIME LOADER] failed to load', src);
      onDone(); // don't let one bad file block the rest
    };
    document.head.appendChild(s);
  }

  function loadNext(i) {
    if (i >= FILES.length) {
      // everything is loaded -- now load the bootstrap/health-check LAST
      loadScript(BASE + 'index.js', function () {
        document.dispatchEvent(new CustomEvent('TSM_RUNTIME_LOADED', { detail: { count: FILES.length } }));
      });
      return;
    }
    loadScript(BASE + FILES[i], function () { loadNext(i + 1); });
  }

  loadNext(0);
})();
