# fly.toml app configuration file generated for tsm-consultz on 2026-06-27T17:08:15Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tsm-consultz'
primary_region = 'dfw'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']


[mounts]
  source = 'tsm_data'
  destination = '/app/data'

[[vm]]
  size = 'shared-cpu-2x'
  cpu_kind = 'shared'
  cpus = 2
  memory_mb = 1024
