#!/usr/bin/env bash
set -euo pipefail

ROOT="/workspaces/tsm-rcm"
cd "$ROOT"

STAMP="$(date +%Y%m%d-%H%M%S)"

SCHOOLS="html/war-rooms/schools-command/schools-command.html"
BRIDGE="html/shared/runtime/mission/mission-sentinel-bridge.js"

echo "============================================================"
echo " TSM SCHOOLS MISSION → SENTINEL FINALIZATION"
echo "============================================================"
echo "Timestamp: $STAMP"
echo

# ------------------------------------------------------------
# 1. BACKUPS
# ------------------------------------------------------------

mkdir -p ".backup/schools-mission-sentinel-$STAMP"

cp "$SCHOOLS" ".backup/schools-mission-sentinel-$STAMP/"
cp "$BRIDGE" ".backup/schools-mission-sentinel-$STAMP/"

echo "[1/6] Backups created."

# ------------------------------------------------------------
# 2. REPLACE GENERIC MISSION → SENTINEL BRIDGE
#
# The old bridge converted the entire mission into ONE generic
# anomaly. That loses the deterministic Schools anomaly details
# already produced by the Schools engine.
#
# The new bridge:
#   - preserves mission classification.anomalies
#   - gives each anomaly a stable mission-scoped ID
#   - removes previous mission-derived anomalies for that mission
#   - leaves non-mission deterministic relay data intact
#   - emits TSM_SENTINEL_REFRESH
# ------------------------------------------------------------

cat > "$BRIDGE" <<'BRIDGE_EOF'
/**
 * TSM Mission → Sentinel Bridge — Phase 4
 *
 * Canonical mission handoff:
 *
 *   Vertical Command
 *       ↓
 *   Mission Core
 *       ↓
 *   Mission Store MISSION_CREATED
 *       ↓
 *   Mission → Sentinel Bridge
 *       ↓
 *   TSM_<VERTICAL>_STRATEGIST_RELAY
 *       ↓
 *   Sentinel
 *
 * Important:
 *   The bridge does NOT invent a generic anomaly from the mission.
 *   It preserves classification.anomalies generated by the vertical
 *   command/engine so Sentinel receives the same deterministic facts.
 */

(function (global) {
  'use strict';

  function relayKeyForVertical(vertical) {
    return 'TSM_' + String(vertical || 'UNKNOWN').toUpperCase() + '_STRATEGIST_RELAY';
  }

  function severityFromPriority(priority) {
    switch (String(priority || '').toLowerCase()) {
      case 'critical': return 'CRIT';
      case 'high':     return 'HIGH';
      case 'medium':   return 'MED';
      default:         return 'LOW';
    }
  }

  function normalizeAnomaly(anomaly, mission, index) {
    anomaly = anomaly || {};

    return {
      id: anomaly.id
        ? String(anomaly.id)
        : 'mission-' + mission.id + '-anomaly-' + index,

      missionId: mission.id,

      vertical: mission.vertical,

      title: anomaly.title ||
        (mission.classification && mission.classification.summary) ||
        (mission.vertical + ' Mission'),

      severity: anomaly.severity ||
        severityFromPriority(
          mission.workflow && mission.workflow.priority
        ),

      exposure:
        anomaly.exposure != null
          ? Number(anomaly.exposure) || 0
          : (
              mission.classification &&
              Number(mission.classification.exposure)
            ) || 0,

      confidence:
        anomaly.confidence != null
          ? anomaly.confidence
          : null,

      rootCause:
        anomaly.rootCause ||
        (mission.classification &&
          mission.classification.summary) ||
        null,

      recommendedAction:
        anomaly.recommendedAction || null,

      impacts:
        anomaly.impacts || {},

      source: anomaly.source || 'mission-core',

      timestamp:
        anomaly.timestamp ||
        mission.createdAt ||
        new Date().toISOString()
    };
  }

  function pushMissionToSentinel(mission) {
    try {
      if (!mission || !mission.vertical || !mission.id) return;

      var classification = mission.classification || {};
      var existing = {};

      var key = relayKeyForVertical(mission.vertical);

      try {
        existing = JSON.parse(
          global.localStorage.getItem(key) || 'null'
        ) || {};
      } catch (e) {
        existing = {};
      }

      /*
       * Preserve deterministic vertical anomalies that were already
       * written by the Command Center, but remove previous mission
       * copies for this exact mission before replacing them.
       */
      var existingAnomalies = Array.isArray(existing.anomalies)
        ? existing.anomalies
        : [];

      existingAnomalies = existingAnomalies.filter(function (a) {
        return !(
          a &&
          a.source === 'mission-core' &&
          a.missionId === mission.id
        );
      });

      var sourceAnomalies =
        Array.isArray(classification.anomalies) &&
        classification.anomalies.length
          ? classification.anomalies
          : [{
              id: 'mission-' + mission.id,
              title:
                classification.summary ||
                (mission.vertical + ' Mission'),
              severity: severityFromPriority(
                mission.workflow &&
                mission.workflow.priority
              ),
              exposure:
                Number(classification.exposure) || 0,
              confidence: null,
              rootCause:
                classification.summary || null,
              recommendedAction: null,
              impacts: {}
            }];

      var missionAnomalies = sourceAnomalies.map(function (a, index) {
        return normalizeAnomaly(a, mission, index);
      });

      /*
       * Avoid duplicate deterministic + mission copies.
       * Mission-derived anomalies become the authoritative version
       * when they carry the same anomaly ID.
       */
      var missionIds = {};
      missionAnomalies.forEach(function (a) {
        missionIds[a.id] = true;
      });

      existingAnomalies = existingAnomalies.filter(function (a) {
        return !(a && missionIds[a.id]);
      });

      existing.anomalies =
        existingAnomalies.concat(missionAnomalies);

      existing.generatedAt = new Date().toISOString();
      existing.missionId = mission.id;
      existing.missionStage = mission.stage || null;

      global.localStorage.setItem(
        key,
        JSON.stringify(existing)
      );

      try {
        global.sessionStorage.setItem(
          key,
          JSON.stringify(existing)
        );
      } catch (e) {}

      global.dispatchEvent(
        new CustomEvent('TSM_SENTINEL_REFRESH', {
          detail: {
            vertical: mission.vertical,
            missionId: mission.id,
            anomalies: missionAnomalies
          }
        })
      );

      console.info(
        '[mission-sentinel-bridge] mission published:',
        mission.id,
        mission.vertical,
        missionAnomalies.length + ' anomaly(s)'
      );

    } catch (e) {
      console.warn(
        '[mission-sentinel-bridge] push failed (non-fatal):',
        e
      );
    }
  }

  var hooked = false;

  /*
   * Shared runtime mission store.
   */
  if (
    global.TSMMissionStore &&
    typeof global.TSMMissionStore.subscribe === 'function'
  ) {
    global.TSMMissionStore.subscribe(
      'MISSION_CREATED',
      pushMissionToSentinel
    );

    hooked = true;
  }

  /*
   * Defensive support for the older instance-based store.
   */
  if (
    !hooked &&
    global.TSMMissionStore &&
    typeof global.TSMMissionStore.addMission === 'function' &&
    typeof global.TSMMissionStore.subscribe !== 'function'
  ) {
    var originalAddMission =
      global.TSMMissionStore.addMission.bind(
        global.TSMMissionStore
      );

    global.TSMMissionStore.addMission = function (mission) {
      var result = originalAddMission(mission);
      pushMissionToSentinel(mission);
      return result;
    };

    hooked = true;
  }

  if (!hooked) {
    console.warn(
      '[mission-sentinel-bridge] Mission store not available yet.'
    );
  }

})(typeof window !== 'undefined' ? window : globalThis);
BRIDGE_EOF

echo "[2/6] Mission → Sentinel bridge finalized."

# ------------------------------------------------------------
# 3. VERIFY THE SCHOOLS MISSION IS USING THE SAME ANOMALIES
# ------------------------------------------------------------

python3 - <<'PY'
from pathlib import Path

p = Path("html/war-rooms/schools-command/schools-command.html")
s = p.read_text()

old = """classification: {
          summary: worst ? worst.rootCause : '',
          anomalies: anomalies,
          exposure: financials.total_exposure || 0,
          exposureCurrency: financials.currency || 'USD',
          source: 'Schools Command Center'
        }"""

new = """classification: {
          summary: worst ? worst.rootCause : 'Schools grant portfolio review',
          anomalies: anomalies,
          exposure: financials.total_exposure || 0,
          exposureCurrency: financials.currency || 'USD',
          source: 'Schools Command Center',
          domain: 'SCHOOLS'
        }"""

if old in s:
    s = s.replace(old, new, 1)
    p.write_text(s)
    print("[3/6] Schools mission classification normalized.")
else:
    if "source: 'Schools Command Center'" in s and "domain: 'SCHOOLS'" in s:
        print("[3/6] Schools mission classification already normalized.")
    else:
        raise SystemExit(
            "[3/6] Expected Schools mission classification block not found."
        )
PY

# ------------------------------------------------------------
# 4. MAKE SURE THE BRIDGE IS LOADED ON SCHOOLS COMMAND
# ------------------------------------------------------------

python3 - <<'PY'
from pathlib import Path

p = Path("html/war-rooms/schools-command/schools-command.html")
s = p.read_text()

bridge = "/html/shared/runtime/mission/mission-sentinel-bridge.js"

if bridge in s:
    print("[4/6] Mission → Sentinel bridge already loaded by Schools Command.")
else:
    # Find the mission store script if one is present.
    candidates = [
        "/html/shared/runtime/mission/mission-store.js",
        "/html/js/tsm-mission-store.js"
    ]

    found = None

    for candidate in candidates:
        if candidate in s:
            found = candidate
            break

    if not found:
        raise SystemExit(
            "[4/6] Could not locate a mission-store script in Schools Command. "
            "Do not insert the bridge blindly."
        )

    needle = f'<script src="{found}"></script>'
    replacement = (
        needle +
        f'\\n<script src="{bridge}"></script>'
    )

    if needle not in s:
        raise SystemExit("[4/6] Mission store script tag format not found.")

    s = s.replace(needle, replacement, 1)
    p.write_text(s)

    print("[4/6] Mission → Sentinel bridge inserted after mission store.")
PY

# ------------------------------------------------------------
# 5. STATIC CONSISTENCY CHECK
# ------------------------------------------------------------

echo "[5/6] Running static consistency checks..."

echo
echo "--- Mission creation ---"
grep -n -A25 -B5 \
  "TSMMissionModel.createMission" \
  "$SCHOOLS" | head -80

echo
echo "--- Mission store ---"
grep -n -A20 -B5 \
  "TSMMissionStore.saveMission" \
  "$SCHOOLS" | head -60

echo
echo "--- Mission → Sentinel bridge ---"
grep -n \
  "mission-sentinel-bridge.js" \
  "$SCHOOLS" || true

echo
echo "--- Bridge mission anomaly preservation ---"
grep -n \
  "classification.anomalies\|MISSION_CREATED\|missionId\|TSM_SENTINEL_REFRESH" \
  "$BRIDGE"

# ------------------------------------------------------------
# 6. DUPLICATE / SYNTAX GUARDS
# ------------------------------------------------------------

echo
echo "[6/6] Final guards..."

node --check <(cat "$BRIDGE") 2>/dev/null || {
  echo "ERROR: Mission → Sentinel bridge failed syntax check."
  exit 1
}

python3 - <<'PY'
from pathlib import Path

p = Path("html/war-rooms/schools-command/schools-command.html")
s = p.read_text()

assert s.count("TSMMissionModel.createMission") >= 1
assert s.count("TSMMissionStore.saveMission") >= 1
assert "classification:" in s
assert "anomalies: anomalies" in s
assert "total_exposure" in s

print("Schools mission assertions: PASS")
PY

echo
echo "============================================================"
echo " SCHOOLS MISSION / SENTINEL PATCH COMPLETE"
echo "============================================================"
echo
echo "Backup:"
echo "  .backup/schools-mission-sentinel-$STAMP/"
echo
echo "Next:"
echo "  1. Run the runtime verification below."
echo "  2. Inspect git diff."
echo "  3. Commit only after the browser check passes."
echo
